# Generated by Django 5.2.1 on 2025-06-07 23:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
