# Generated by Django 5.2.1 on 2025-06-07 23:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_perfil_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
