# Generated by Django 5.2.1 on 2025-06-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_perfil_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='bio',
            new_name='biografia',
        ),
    ]
